In [1]:
from numpy import array
import keras
from keras.models import Sequential, Model
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Input
from keras.layers import TimeDistributed
import tensorflow as tf

import keras.backend as K

In [2]:
# physical_devices = tf.config.list_physical_devices('GPU')
# tf.config.experimental.set_memory_growth(physical_devices[0], enable=True)
# print (physical_devices)

IndexError: list index out of range

In [65]:
length = 5
seq = array([i/float(length) for i in range(length)],'float64')
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length, 1)
print ("X: ", X.shape, X)
print ("y: ", y.shape, y)


# define LSTM configuration
n_neurons = length
n_batch = 1
n_epoch = 1000

# create LSTM
model = Sequential()
layer1 = LSTM(n_neurons, input_shape=(length, 1), return_sequences=True)
model.add(layer1)

# 
layer2 = Dense(n_neurons)
model.add(layer2)

# 
print ("")
print ("STARTING PREDICTION: ", tf.print(layer1(X)))
print ("")
print ("")
print ("")
#print ("STARTING PREDICTION: ", tf.print(layer1(X)))

# # Define custom loss
# def custom_loss(layer1):
    
#     # Create a loss function that adds the MSE loss to the mean of all squared activations of a specific layer
#     def loss(y_true,y_pred):
#         res = K.mean(K.square(y_pred - y_true) + K.square(layer1(X)), axis=-1)
#         #print ("Resulting error: ", tf.print(res))
#         print (tf.print(''))
#         print (tf.print(layer1(X)))
#         print (tf.print(''))
#         #ctr+=1
#         return res
    
#     # Return a function
#     return loss

# #global ctr
# ctr=0
# # compile model
# model.compile(loss=custom_loss(layer1), optimizer='adam')

# # train LSTM
# model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=0)
# print ("DONE")

X:  (1, 5, 1) [[[0. ]
  [0.2]
  [0.4]
  [0.6]
  [0.8]]]
y:  (1, 5, 1) [[[0. ]
  [0.2]
  [0.4]
  [0.6]
  [0.8]]]


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

[[[0 0 0 0 0]
  [0.00652822526 0.0233266409 0.0151992282 0.0197222568 -0.0229926836]
  [0.0159459766 0.0626661405 0.0442581847 0.0565559976 -0.0625331104]
  [0.0259212554 0.111707494 0.0842512548 0.108747967 -0.111463018]
  [0.0349170268 0.164147601 0.13072823 0.174196288 -0.162145495]]]
STARTING PREDICTION:  None





In [46]:
# evaluate
import numpy as np
result = model.predict(X, batch_size=n_batch, verbose=0)
print ("FUL RESTUL: ", result)
#print ("result: ", result.shape, np.round(result.mean(2),2))
#for value in result[0,:,0]:
#	print('%.1f' % value)

FUL RESTUL:  [[0.002135   0.19825363 0.39113748 0.5685448  0.7384079 ]]


In [13]:
# Build a model
inputs = Input(shape=(128,))
layer1 = Dense(64, activation='relu')(inputs)
layer2 = Dense(64, activation='relu')(layer1)
predictions = Dense(10, activation='softmax')(layer2)
model = Model(inputs=inputs, outputs=predictions)

def custom_loss(y_true, y_pred):
            
    # calculate loss, using y_pred
        
    return loss
  
model.compile(loss=custom_loss, optimizer='adam')


In [15]:
# Build a model
inputs = Input(shape=(128,))
layer1 = Dense(64, activation='relu')(inputs)
layer2 = Dense(64, activation='relu')(layer1)
predictions = Dense(10, activation='softmax')(layer2)
model = Model(inputs=inputs, outputs=predictions)

# Define custom loss
def custom_loss(layer):

    # Create a loss function that adds the MSE loss to the mean of all squared activations of a specific layer
    def loss(y_true,y_pred):
        return K.mean(K.square(y_pred - y_true) + K.square(layer), axis=-1)
   
    # Return a function
    return loss
    
# Compile the model
model.compile(optimizer='adam',
              loss=custom_loss(layer1), # Call the loss function with the selected layer
              metrics=['accuracy'])

model.summary()

# train
model.fit(data, labels)  

Model: "functional_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_5 (InputLayer)         [(None, 128)]             0         
_________________________________________________________________
dense_13 (Dense)             (None, 64)                8256      
_________________________________________________________________
dense_14 (Dense)             (None, 64)                4160      
_________________________________________________________________
dense_15 (Dense)             (None, 10)                650       
Total params: 13,066
Trainable params: 13,066
Non-trainable params: 0
_________________________________________________________________


NameError: name 'data' is not defined